import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";



import { ClerkProvider } from "@clerk/nextjs";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

  export default function RootLayout({
  children,
}){
   return (
    <ClerkProvider >
     <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >

      <body className={ `min-h-full flex flex-col ${outfit.className}`} >{children}
       <Toaster /></body>
    </html>

    </ClerkProvider>
 
    
       
   
  )
}
  
